# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-scaffold-for-gh-pages" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Handling Reading
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
  - "bin/"
  - "script/"
  - "README.md"

## GitHub Pages Overrides (Configuration settings you cannot change)
## (Ref.: https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides)
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false

## GitHub Pages Defaults (Defaults you can change)
## (Ref.: https://help.github.com/articles/using-jekyll-with-pages/#defaults-you-can-change)
# github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

  ## Jekyll Plugins with GitHub Pages
  ## (Ref.: https://help.github.com/articles/using-jekyll-plugins-with-github-pages/)
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

  # - jekyll-feed
